import sys
import cx_Oracle
import datetime
from array import array

#This class deals with the splash/login menu
class Booking:
	email = ""
	name = ""

	#This is the init file. A connection string is required to setup the class.
	def __init__(self, connectionString):
		self.connectionString = connectionString
	

	def cancelBooking(self):
		print("cancel Booking")
			
	
	def makeBooking(self, email):
		#Make a booking. 
		#A user should be able to select a flight (or flights when there are connections) from those returned for a search and book it. 
		
		#The system should get the name of the passenger and check if the name is listed in the passenger table with the user email. 
		#If not, the name and the country of the passenger should be added to the passenger table with the user email. 
		
		#Your system should add rows to tables bookings and tickets to indicate that the booking is done 
		#(a unique ticket number should be generated by the system). 
		
		#Your system can be used by multiple users at the same time and overbooking is not allowed. 
		#Therefore, before your update statements, you probably want to check if the seat is still available and place this checking and your update statements within a transaction. 
		
		#Finally the system should return the ticket number and a confirmation message if a ticket is issued or a descriptive message if a ticket cannot be issued for any reason.
		
		#flightno	char(6),
		#fare		char(2),
		#dep_date	date,
		
		userName = input("\nPlease input the name of the passenger:")
		
		if(self.isUserAPassenger(userName,email)==False):
			self.addUserToPassengerList(userName,email)
			print("Not a passenger")
		else:
			print("Passenger")
		
	
		
	
	#checks to see if a user has been a passenger. 
	def isUserAPassenger(self,name,email):
		#this is the query to see if a user exists in the passenger's table
		query = "SELECT * FROM passengers WHERE TRIM(email)=:u_email and TRIM(name)=:u_name"
		
		#connect to SQL and execute query.
		connection = cx_Oracle.connect(self.connectionString)
		curs = connection.cursor()
		curs.execute(query, u_name=name, u_email=email)
		rows = curs.fetchone()
		
		#if number of hits ==0: user does not exit
		if (curs.rowcount ==0):
			curs.close()
			connection.close()
			return False
		else:
			return True
		
		
		
	def addUserToPassengerList(self,name,email):
		print("added user")
		
	
	#String format for double from:
	#http://stackoverflow.com/questions/455612/limiting-floats-to-two-decimal-points
	def listExistingBookings(self,email):
			
		ticketNumber = self.listAllUserBookings(email)
		
		if (ticketNumber >0):
			self.viewBookingDetails(ticketNumber)
			
		
	
	
	def viewBookingDetails(self,ticketNumber):
		#this is the query to view the full details of a specific booking
		query = "SELECT * FROM bookings WHERE tno=:ticketNum"
		
		#connect to SQL and execute query.
		connection = cx_Oracle.connect(self.connectionString)
		curs = connection.cursor()
		curs.execute(query, ticketNum=ticketNumber)
		rows = curs.fetchone()
		
		#if number of hits ==0: user has no bookings in the system
		if (curs.rowcount ==0):
			curs.close()
			connection.close()
			print("\nBooking no longer exists.")
			return 0
		
		else:
			#this prints a formated heading for the ticket info
			print("%s %s %s %s %s" % ("Ticket No".ljust(11), "Flight No".ljust(11), "Fare".ljust(6), "Depart Date".ljust(12), "Seat"))
		
			#formats data
			flightno = rows[1].ljust(11)
			fare = rows[2].ljust(6)
			departDate = rows[3]
			departDateStr = str(int(departDate.day)) + "-" + str(int(departDate.month)) + "-" + str(int(departDate.year))
			seat = rows[4]
			
			#prints it
			print("%s %s %s %s %s" %(str(ticketNumber).ljust(11), flightno.ljust(11), fare.ljust(6), departDateStr.ljust(12), seat))


		
	def listAllUserBookings(self,email):
		#query merges ticket and booking tables and retrives the tno, name, dep_date, paid_price
		query = "SELECT t.tno, t.name, b.dep_date, t.paid_price FROM tickets t, bookings b WHERE t.tno=b.tno AND TRIM(t.email)=:u_email"
		
				
		#an array of totalHits size to contain a list of all the ticket numbers
		ticketArray = array("i")
		#item number in booking list
		itemNum = 0
		
		#connect to SQL and execute query.
		connection = cx_Oracle.connect(self.connectionString)
		curs = connection.cursor()
		curs.execute(query, u_email=email)
		rows = curs.fetchone()
		
		#if number of hits ==0: user has no bookings in the system
		if (curs.rowcount ==0):
			curs.close()
			connection.close()
			print("\nUser has no previous bookings.")
			return 0
		
		else:
			#this prints a formated heading for the ticket info
			print("%s %s %s %s %s" % ("Item No".ljust(8),"Ticket No".ljust(11), "Name".ljust(22), "Depart Date".ljust(12), "Price"))
			
			while (rows):
				itemNum += 1
				ticketArray.append(self.extractPartialBookingDetails(itemNum,rows))
				rows = curs.fetchone()
				
			curs.close()
			connection.close()
			print("\nWould you like a booking?")
			userInput = self.verifyUInt("Please enter an item number or press 0 to return to the main menu.", len(ticketArray))
			if(userInput >0):
				return ticketArray[userInput-1]
			else:
				return 0
		
	
		
	def extractPartialBookingDetails(self, itemNum,item):	

		#Splits up
		ticketNum=int(item[0])
		name=item[1]
		departDate=item[2]
		price=item[3]
		
		#converts the depart date to a usable string
		departDateStr = str(int(departDate.day)) + "-" + str(int(departDate.month)) + "-" + str(int(departDate.year))
				
		#prints out the row
		print("%s %s %s %s %.2f" %(str(itemNum).ljust(8), str(ticketNum).ljust(11), name.ljust(22), departDateStr.ljust(12), price))
		
		return ticketNum
		
	
	#this verifies that a user input is an int between 0 and Max Size.
	def verifyUInt(self, message, maxSize):
		userInput= 0
		while (True):
			try:
				userInput = int(input(message));
				break
			except ValueError:
				print("\nInvalid option.")

		while((userInput < 0) or (userInput > maxSize)):
			print("\nInvalid option.")
			userInput = int(input(message));
			
		return userInput
			
